### ISSUE TITLE
Docs say SCRIPT_NAME can be empty, code disagrees

### ISSUE THREAD

**Issue by gdamjan** [slimphp/Slim#1322]
Here in the [docs](http://docs.slimframework.com/environment/overview/) I'm reading that SCRIPT_NAME can be empty:

> The initial portion of the request URI’s “path” that corresponds to the physical directory in which the Slim application is installed — so that the application knows its virtual “location”. This may be an empty string if the application is installed in the top-level of the public document root directory. This will never have a trailing slash.

But instead, when I run my slim hello world, in my special environment (I'm testing a specific uwsgi configuration), where SCRIPT_NAME is the empty string it fails with:

```
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'strpos(): Empty needle' in /home/damjan/my-work/phar-test/vendor/slim/slim/Slim/Environment.php:135
Stack trace:
#0 [internal function]: Slim\Slim::handleErrors(2, 'strpos(): Empty...', '/home/damjan/my...', 135, Array)
#1 /home/damjan/my-work/phar-test/vendor/slim/slim/Slim/Environment.php(135): strpos('/hello/worlasda...', '')
#2 /home/damjan/my-work/phar-test/vendor/slim/slim/Slim/Environment.php(76): Slim\Environment->__construct()
#3 /home/damjan/my-work/phar-test/vendor/slim/slim/Slim/Slim.php(159): Slim\Environment::getInstance()
#4 /home/damjan/my-work/phar-test/vendor/slim/slim/Slim/Helper/Set.php(228): Slim\Slim->Slim\{closure}(Object(Slim\Helper\Set))
#5 /home/damjan/my-work/phar-test/vendor/slim/slim/Slim/Helper/Set.php(88): Slim\Helper\Set->Slim\Helper\{closure}(Object(Slim\Helper\Set))
#6 /home/damjan/my-work/phar-test/vendor/slim/slim/Slim/Helper/Set.php(185): Slim\Helper\Set->get('environment')
#7 /home/damjan/my-work/phar-test/vendor/slim/slim in /home/damjan/my-work/phar-test/vendor/slim/slim/Slim/Environment.php on line 135
```

slim is version 2.6.2

I wonder are the docs wrong or the code

**Comment by geggleto** [comment]
Doc's are wrong... as far as I know script_name cannot be empty.

Offending Code

``` php
//...
            // Physical path
            if (strpos($requestUri, $scriptName) !== false) {
                $physicalPath = $scriptName; // <-- Without rewriting
            } else {
                $physicalPath = str_replace('\\', '', dirname($scriptName)); // <-- With rewriting
            }
//...
```

**Comment by akrabat** [comment]
As Slim 3 is released, we are only fixing Security issues on Slim 2.
