### ISSUE TITLE
Error launching phpunit on Windows

### ISSUE THREAD

**Issue by DavidePastore** [slimphp/Slim#1944]
Hi,
I'm trying to launch phpunit on my Windows pc and it shows me these errors:

```
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.

...............................................................  63 / 552 ( 11%)
............................................................... 126 / 552 ( 22%)
..........................F...............SSSSSSSSSSSSS........ 189 / 552 ( 34%)
............................................................... 252 / 552 ( 45%)
............................................................... 315 / 552 ( 57%)
............................................................... 378 / 552 ( 68%)
............................................................R.. 441 / 552 ( 79%)
............................................................... 504 / 552 ( 91%)
................................................

Time: 2.16 seconds, Memory: 12.00MB

There was 1 failure:

1) Slim\Tests\Handlers\ErrorTest::testPreviousException
Expectation failed for method name is equal to <string:logError> when invoked 1 time(s)
Parameter 0 for invocation Slim\Handlers\AbstractError::logError('Slim Application Error:\nType:...ting.\n') does not match expected value.
Failed asserting that 'Slim Application Error:
Type: Exception
Message: Second Oops
File: C:\Users\Davide\git\Slim\tests\Handlers\ErrorTest.php
Line: 94
Trace: #0 [internal function]: Slim\Tests\Handlers\ErrorTest->testPreviousException()
#1 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestCase.php(909): ReflectionMethod->invokeArgs(Object(Slim\Tests\Handlers\ErrorTest), Array)
#2 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestCase.php(768): PHPUnit_Framework_TestCase->runTest()
#3 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestResult.php(612): PHPUnit_Framework_TestCase->runBare()
#4 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestCase.php(724): PHPUnit_Framework_TestResult->run(Object(Slim\Tests\Handlers\ErrorTest))
#5 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestSuite.php(747): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#6 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#7 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#8 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\TextUI\Command.php(149): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#9 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\TextUI\Command.php(100): PHPUnit_TextUI_Command->run(Array, true)
#10 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\phpunit(47): PHPUnit_TextUI_Command::main()
#11 {main}
Previous error:
Type: Exception
Message: First Oops
File: C:\Users\Davide\git\Slim\tests\Handlers\ErrorTest.php
Line: 93
Trace: #0 [internal function]: Slim\Tests\Handlers\ErrorTest->testPreviousException()
#1 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestCase.php(909): ReflectionMethod->invokeArgs(Object(Slim\Tests\Handlers\ErrorTest), Array)
#2 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestCase.php(768): PHPUnit_Framework_TestCase->runTest()
#3 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestResult.php(612): PHPUnit_Framework_TestCase->runBare()
#4 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestCase.php(724): PHPUnit_Framework_TestResult->run(Object(Slim\Tests\Handlers\ErrorTest))
#5 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestSuite.php(747): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#6 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\Framework\TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#7 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#8 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\TextUI\Command.php(149): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#9 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\src\TextUI\Command.php(100): PHPUnit_TextUI_Command->run(Array, true)
#10 C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\phpunit(47): PHPUnit_TextUI_Command::main()
#11 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
' contains "type: exception
message: second oops" and contains "previous error:
type: exception
message: first oops".

C:\Users\Davide\git\Slim\Slim\Handlers\AbstractError.php:53
C:\Users\Davide\git\Slim\Slim\Handlers\Error.php:55
C:\Users\Davide\git\Slim\tests\Handlers\ErrorTest.php:96
C:\Users\Davide\git\Slim\vendor\phpunit\phpunit\phpunit:47

FAILURES!
Tests: 552, Assertions: 885, Failures: 1, Skipped: 13, Risky: 1.
Script php vendor/phpunit/phpunit/phpunit handling the phpunit event returned with error code 1
```

My PHP version is **5.6.21**.

**Comment by geggleto** [comment]
Can you check what tag of Slim you are using?

**Comment by DavidePastore** [comment]
I'm even with the `3.x` branch: https://github.com/slimphp/Slim/commit/a63b393a5d5d8ebf774c6716059b5ec151ae7198 .

**Comment by geggleto** [comment]
Confirming the result on PHP 5.6.3, Also running windows... using: `call vendor/bin/phpunit`

**Comment by geggleto** [comment]
Ah... I believe the problem relates to how slim attempts to log things to the "error_log" in Windows.
