### ISSUE TITLE
Invokable class middleware not passing $next 

### ISSUE THREAD

**Issue by SusanthCom** [slimphp/Slim#1950]
Invokable class middleware not passing `$next`

``` php
<?php
require_once __DIR__ . "/../vendor/autoload.php";

class SampleMiddleware
{
    public function __invoke($request, $response, $nex)
    {
        $response->getBody()->write(' __BEFORE__ ');
        $response = $next($request, $response);
        $response->getBody()->write(' __AFTER__ ');

        return $response;
    }
}

$slimSettings['settings']['displayErrorDetails']    = true;
$slimSettings['settings']['addContentLengthHeader'] = false;

$app = new \Slim\App($slimSettings);

$app->add( new SampleMiddleware() );

$app->get('/', function ($request, $response, $args) {
    return $response->getBody()->write(" Hello... ");
});

$app->run();
```

Reports Error 

```
Notice: Undefined variable: next in /sh/slab/www-root/client-works/cd.tiger/www/index.php on line 9
Slim Application Error
The application could not run because of the following error:

Details

Type: Error
Message: Function name must be a string
File: /sh/slab/www-root/client-works/cd.tiger/www/index.php
Line: 9
Trace

#0 [internal function]: SampleMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#1 /sh/slab/www-root/client-works/cd.tiger/app-sts/php-root/composer-lib/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(SampleMiddleware), Array)
#2 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#3 /sh/slab/www-root/client-works/cd.tiger/app-sts/php-root/composer-lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#4 /sh/slab/www-root/client-works/cd.tiger/app-sts/php-root/composer-lib/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 /sh/slab/www-root/client-works/cd.tiger/app-sts/php-root/composer-lib/vendor/slim/slim/Slim/App.php(337): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /sh/slab/www-root/client-works/cd.tiger/app-sts/php-root/composer-lib/vendor/slim/slim/Slim/App.php(298): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /sh/slab/www-root/client-works/cd.tiger/www/index.php(27): Slim\App->run()
#8 {main}
```

upon debugging, found that `$next` is null !

**Comment by akrabat** [comment]
You have a misspelling in your function definition:

```
public function __invoke($request, $response, $nex)
```

should be:

```
public function __invoke($request, $response, $next)
```

**Comment by SusanthCom** [comment]
@akrabat  Thank you Very much. Now working.

Will do more research before posting here. 
Sorry 😢

**Comment by akrabat** [comment]
@SusanthCom No problem. Glad it's working for you now.
