### ISSUE TITLE
PHP Unit mock and Slim Framework Call to undefined method 

### ISSUE THREAD

**Issue by cpapidas** [slimphp/Slim#2198]
Hello,

I am trying to test the following code with phpunit mocks but Slim throws the error **Call to undefined method** 

slim version: last
php version: 7

My Service file is
```php
class ProvidersService
{

   ...
    public function __construct(HttpCurl $httpCurl, ResponseBuilder $responseBuilder, $settings)
    {
        ....
    }

    public function createShortLink($providerName, $longUrl)
    {
        return something here ....
    }

 ....

}
```

my test file is 

```php
public function testBitlyCreateShortLink()
    {

        $stub = $this->getMock(\Services\ProvidersService::class, ['createShortLink']);
        // or
// $stub = $this->getMockBuilder(\Services\ProvidersService::class)->setMethods(['createShortLink'])->getMock();
        $stub->expects($this->any())->method('createShortLink')->with(1);

        $response = $this->runApp('POST', '/url-here', array(params here));

        $this->assertEquals($response, 1);

    }
```

and i get the following error
```
Details

Type: Error
Message: Call to undefined method Services\ProvidersService::createShortLink()
File: /vagrant/shortener-mock/src/Controllers/ShortenController.php
Line: 27
Trace

#0 [internal function]: Controllers\ShortenController->post(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#1 /vagrant/shortener-mock/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /vagrant/shortener-mock/vendor/slim/slim/Slim/Route.php(344): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /vagrant/shortener-mock/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 /vagrant/shortener-mock/vendor/slim/slim/Slim/Route.php(316): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 /vagrant/shortener-mock/vendor/slim/slim/Slim/App.php(476): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /vagrant/shortener-mock/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /vagrant/shortener-mock/vendor/slim/slim/Slim/App.php(370): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /vagrant/shortener-mock/tests/Functional/BaseTestCase.php(97): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /vagrant/shortener-mock/tests/Functional/ShortenProviders/BitlyShortenProviderTest.php(37): Tests\Functional\BaseTestCase->runApp('POST', '/api/v1/shorten', Array)
#10 [internal function]: Tests\Functional\ShortenProviders\BitlyShortenProviderTest->testBitlyCreateShortLink()
#11 /vagrant/shortener-mock/vendor/phpunit/phpunit/src/Framework/TestCase.php(1054): ReflectionMethod->invokeArgs(Object(Tests\Functional\ShortenProviders\BitlyShortenProviderTest), Array)
#12 /vagrant/shortener-mock/vendor/phpunit/phpunit/src/Framework/TestCase.php(905): PHPUnit_Framework_TestCase->runTest()
#13 /vagrant/shortener-mock/vendor/phpunit/phpunit/src/Framework/TestResult.php(686): PHPUnit_Framework_TestCase->runBare()
#14 /vagrant/shortener-mock/vendor/phpunit/phpunit/src/Framework/TestCase.php(860): PHPUnit_Framework_TestResult->run(Object(Tests\Functional\ShortenProviders\BitlyShortenProviderTest))
#15 /vagrant/shortener-mock/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#16 /vagrant/shortener-mock/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(517): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#17 /vagrant/shortener-mock/vendor/phpunit/phpunit/src/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array, true)
#18 /vagrant/shortener-mock/vendor/phpunit/phpunit/src/TextUI/Command.php(116): PHPUnit_TextUI_Command->run(Array, true)
#19 /vagrant/shortener-mock/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()
```

Do you have any ideas what am i missing ?

**Comment by tuupola** [comment]
Do you actually pass the stub to your`ProvidersService` somewhere?

**Comment by Marcin-TA** [comment]
Is there a way to mock API request in Slim 4?
