### ISSUE TITLE
Routing. Using pattern

### ISSUE THREAD

**Issue by launcelot66** [slimphp/Slim#2339]
```
$app->get('/{type:(CARS_FOREIGN|CARS_NATIVE|TRUCKS_NATIVE|TRUCKS_FOREIGN|BUS|SPECIAL_TECH_NATIVE|SPECIAL_TECH_FOREIGN|AGRICULTURAL_MACHINERY|TRACTOR|ENGINE|MOTORCYCLE)}', function (Request $request, Response $response, array $args) {
    return $this->renderer->render($response, 'example.php', $args);
});
```
then i got an error like this:

> Type: FastRoute\BadRouteException
> Message: Regex "(CARS_FOREIGN|CARS_NATIVE|TRUCKS_NATIVE|TRUCKS_FOREIGN|BUS|SPECIAL_TECH_NATIVE|SPECIAL_TECH_FOREIGN|AGRICULTURAL_MACHINERY|TRACTOR|ENGINE|MOTORCYCLE)" for parameter "type" contains a capturing group
> File: /Users/lans/Documents/projects/acat-online/exampleSite/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php
> Line: 108

trace:
Trace

```
#0 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php(76): FastRoute\DataGenerator\RegexBasedAbstract->buildRegexForRoute(Array)
#1 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php(20): FastRoute\DataGenerator\RegexBasedAbstract->addVariableRoute('GET', Array, 'route0')
#2 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/nikic/fast-route/src/RouteCollector.php(36): FastRoute\DataGenerator\RegexBasedAbstract->addRoute('GET', Array, 'route0')
#3 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/slim/slim/Slim/Router.php(227): FastRoute\RouteCollector->addRoute(Array, '/{type:(CARS_FO...', 'route0')
#4 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/nikic/fast-route/src/functions.php(24): Slim\Router->Slim\{closure}(Object(FastRoute\RouteCollector))
#5 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/slim/slim/Slim/Router.php(238): FastRoute\simpleDispatcher(Object(Closure), Array)
#6 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/slim/slim/Slim/Router.php(191): Slim\Router->createDispatcher()
#7 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/slim/slim/Slim/App.php(549): Slim\Router->dispatch(Object(Slim\Http\Request))
#8 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/slim/slim/Slim/App.php(473): Slim\App->dispatchRouterAndPrepareRoute(Object(Slim\Http\Request), Object(Slim\Router))
#9 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/slim/slim/Slim/App.php(370): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /Users/lans/Documents/projects/acat-online/exampleSite/vendor/slim/slim/Slim/App.php(295): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 /Users/lans/Documents/projects/acat-online/exampleSite/public/index.php(29): Slim\App->run()
#13 {main}
```

**Comment by geggleto** [comment]
Your regex appears to be incorrect; Routing is actually not handled by slim; Slim wraps around FastRoute.

**Comment by launcelot66** [comment]
@geggleto Can you help me with this? (some example how to include FastRoute to slim 3.9)

**Comment by akrabat** [comment]
Remove the brackets:

```
$app->get('/{type:CARS_FOREIGN|CARS_NATIVE|TRUCKS_NATIVE|TRUCKS_FOREIGN|BUS|SPECIAL_TECH_NATIVE|SPECIAL_TECH_FOREIGN|AGRICULTURAL_MACHINERY|TRACTOR|ENGINE|MOTORCYCLE}', function (Request $request, Response $response, array $args) {
    return $this->renderer->render($response, 'example.php', $args);
});
```

Further information in [defining routes](https://github.com/nikic/FastRoute#defining-routes):

> Custom patterns for route placeholders cannot use capturing groups. For example `{lang:(en|de)}` is not a valid placeholder, because `()` is a capturing group. Instead you can use either `{lang:en|de}` or `{lang:(?:en|de)}`.
