### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by noturnocs** [slimphp/Slim#2699]
error: "Malformed UTF-8 characters, possibly incorrectly encoded"
use: nginx and php73-fpm

data response:
```php
Array
(
    [ext] => Array
        (
            [0] => Array
                (
                    [comanda] => 19
                    [taxa] => 0
                    [caixa] => 
                    [ajuste] => 0
                    [cc] => 0
                    [cd] => 0
                    [ccp] => 0
                )

            [1] => Array
                (
                    [0] => Array
                        (
                            [0] => Cachorro quente
                            [1] => 1
                            [2] => 50
                        )

                    [1] => Array
                        (
                            [0] => Amendoim crocante sabor cebola e salsa
                            [1] => 1
                            [2] => 50
                        )

                )

            [2] => 2
            [3] => Array
                (
                )

            [4] => 0
            [5] => Array
                (
                )

            [6] => 0
            [7] => Array
                (
                )

            [8] => 0
        )

    [status] => 
    [legenda] => Array
        (
            [0] => stdClass Object
                (
                    [id] => ext
                    [legenda] => Não identificado
                )

            [1] => stdClass Object
                (
                    [id] => total
                    [legenda] => Todos
                )

        )

    [nivel] => 2
    [total] => Array
        (
            [0] => Array
                (
                    [comanda] => 19
                    [taxa] => 0
                    [caixa] => 
                    [ajuste] => 0
                    [cc] => 0
                    [cd] => 0
                    [ccp] => 0
                )

            [1] => Array
                (
                    [0] => Array
                        (
                            [0] => Cachorro quente
                            [1] => 1
                            [2] => 50
                        )

                    [1] => Array
                        (
                            [0] => Amendoim crocante sabor cebola e salsa
                            [1] => 1
                            [2] => 50
                        )

                )

            [2] => 2
            [3] => Array
                (
                )

            [4] => Array
                (
                    [0] => 0
                    [1] => 0
                )

            [5] => Array
                (
                )

            [6] => Array
                (
                    [0] => 0
                    [1] => 0
                )

            [7] => Array
                (
                )

            [8] => 0
        )

)
```
error in "Não identificado" if remove "ã" pass and work.

**Comment by l0gicgate** [comment]
What version of Slim are you running? When is the error occurring? Can you provide error stack trace please? Thanks

**Comment by noturnocs** [comment]
3.11.0

```php
{
    "message": "Slim Application Error",
    "exception": [
        {
            "type": "RuntimeException",
            "code": 5,
            "message": "Malformed UTF-8 characters, possibly incorrectly encoded",
            "file": "\/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/Http\/Response.php",
            "line": 353,
            "trace": [
                "#0 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/index.php(2651): Slim\\Http\\Response->withJson(Array, 200)",
                "#1 [internal function]: Closure->{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#2 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#3 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/Route.php(335): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Object(Closure), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#4 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/classes\/gastroz.class.php(140): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#5 [internal function]: Auth->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))",
                "#6 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/DeferredCallable.php(43): call_user_func_array(Object(Auth), Array)",
                "#7 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))",
                "#8 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))",
                "#9 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(117): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#10 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/Route.php(313): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#11 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/App.php(513): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#12 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(117): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#13 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/App.php(406): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#14 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/vendor\/slim\/slim\/Slim\/App.php(314): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#15 \/usr\/local\/nginx\/html\/pHpServer-ADm\/api\/index.php(4293): Slim\\App->run()",
                "#16 {main}"
            ]
        }
    ]
}
```

error in return response

**Comment by froschdesign** [comment]
@noturnocs 
Please format your code blocks by placing triple backticks. This increases the readability enormously.
See also in the GitHub Help: [Creating and highlighting code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

Thanks!

**Comment by noturnocs** [comment]
solved!
->withHeader('Content-type', 'application/json', 'charset=utf-8');
add charset=utf-8 in return

**Comment by RyanNerd** [comment]
@noturnocs This may be of help: https://stackoverflow.com/questions/46305169/php-json-encode-malformed-utf-8-characters-possibly-incorrectly-encoded

**Comment by noturnocs** [comment]
@RyanNerd no work

**Comment by noturnocs** [comment]
@RyanNerd not work, replace char for ?

**Comment by l0gicgate** [comment]
I can't replicate this behavior at all..

With the following:
```php
<?php

use Slim\App;

require __DIR__ . '/vendor/autoload.php';

$app = new App();

$app->get('/', function ($request, $response) {
        return $response->withJson('Não identificado');
});

$app->run();
```

The output is:
```
"N\u00e3o identificado"
```

**Comment by l0gicgate** [comment]
I’m closing this as there hasn’t been any new feedback and I can’t reproduce the issue on my end.

**Comment by kdekooter** [comment]
In my case this error was triggered by UUIDs in the result set. The fix is to add this flag to your database configuration:
`PDO::DBLIB_ATTR_STRINGIFY_UNIQUEIDENTIFIER => true`
