### ISSUE TITLE
Is it possible to get more information for a HttpNotFoundException?

### ISSUE THREAD

**Issue by notflip** [slimphp/Slim#3021]
In my server logs I'm seeing a lot of 404 errors coming in, the issue is I can't seem to find out what is causing them, is it possible in some way to add more information into the errors?

I'm using the ErrorMiddleware as follows

```php
<?php
return function ($app) {
    $app->addBodyParsingMiddleware();
    $app->addRoutingMiddleware();

    // Error Middleware
    $loggerFactory = $app->getContainer()->get(\App\Factory\LoggerFactory::class);
    $logger = $loggerFactory->addFileHandler('error.log')->createInstance('error');
    $app->addErrorMiddleware(true, true, true, $logger);
};

```

This is the error message
```
[2020-11-15T12:20:54.214532+01:00] error.ERROR: 404 Not Found Type: Slim\Exception\HttpNotFoundException Code: 404 Message: Not found.
File: /var/www/initialdeck.notflip.be/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php Line: 93

Trace:
#0 /var/www/initialdeck.notflip.be/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting()
#1 /var/www/initialdeck.notflip.be/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process() 
#2 /var/www/initialdeck.notflip.be/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle() 
#3 /var/www/initialdeck.notflip.be/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process()
#4 /var/www/initialdeck.notflip.be/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#5 /var/www/initialdeck.notflip.be/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#6 /var/www/initialdeck.notflip.be/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#7 /var/www/initialdeck.notflip.be/public/index.php(19): Slim\App->run()
#8 {main}
```

**Comment by l0gicgate** [comment]
You could make a custom error handler to extract the URI from the `ServerRequest`. You can do `$e->getRequest()` on the `HttpNotFoundException` to obtain the request that caused the error to be raised. From there you can extract the URI that caused it and log it to add more insight to your logs.

**Comment by notflip** [comment]
> You could make a custom error handler to extract the URI from the `ServerRequest`. You can do `$e->getRequest()` on the `HttpNotFoundException` to obtain the request that caused the error to be raised. From there you can extract the URI that caused it and log it to add more insight to your logs.

Do you mean overwriting the ErrorMiddleware with my own implementation?

**Comment by l0gicgate** [comment]
@notflip no, I mean you could implement your own custom `ErrorHandler` where you could add custom logging.

**Example Custom Handler:**
```php
<?php
declare(strict_types=1);

use Slim\Handlers\ErrorHandler;

class CustomErrorHandler extends ErrorHandler
{
    protected function logError(string $error): void
    {
        $uri = $this->request->getUri();

        // We add the requested URI here so you can get more context within your logs
        $this->logger->error($error, ['requestedUri' => (string) $uri]);
    }
}
```

```php
return function ($app) {
    $app->addBodyParsingMiddleware();
    $app->addRoutingMiddleware();

    // Logger
    $loggerFactory = $app->getContainer()->get(\App\Factory\LoggerFactory::class);
    $logger = $loggerFactory->addFileHandler('error.log')->createInstance('error');

    // Custom Handler
    $customErrorHandler = new CustomErrorHandler(
        $app->getCallableResolver(),
        $app->getResponseFactory(),
        $logger,
    );

    // Error Middleware
    $errorMiddleware = $app->addErrorMiddleware(true, true, true, $logger);
    $errorMiddleware->setDefaultErrorHandler($customErrorHandler);
};
```

**Comment by notflip** [comment]
@l0gicgate Thanks for clarifying! That makes sense
