### ISSUE TITLE
$response->withJson() returns error: Call to undefined method Slim\Psr7\Response::withJson()

### ISSUE THREAD

**Issue by jh97uk** [slimphp/Slim#3039]
I have this code:

```
$app->get('/', function (Request $request, Response $response, $args) use($database){
    $response->withJson([]);
    return $response->withHeader('Content-Type', 'application/json');
});
```

But it always returns this error:

```
#0 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array)
#1 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array)
#2 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Psr7\Request))
#3 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request))
#4 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request))
#5 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Psr7\Request))
#6 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Routing\RouteRunner->handle(Object(Slim\Psr7\Request))
#7 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner))
#8 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Psr7\Request))
#9 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous))
#10 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Psr7\Request))
#11 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous))
#12 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Psr7\Request))
#13 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request))
#14 /Users/user/Documents/Programming/php/testing/test1/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Psr7\Request))
#15 /Users/user/Documents/Programming/php/testing/test1/public/index.php(48): Slim\App->run()
#16 {main}
```

I'm just following whats on the docs, but it doesnt seem to be working.

**Comment by l0gicgate** [comment]
You need to install Slim-Http decorators as per the docs. Paste your index.php so we can help you further.

**Comment by ghost** [comment]
Here is the solution:

1. Add this in your `composer.json` ->  `slim/http` 
2. Add `Slim\Http\Response as Response` instead `Psr\Http\Message\ResponseInterface as Response`

And you will be able to use `$response->withJson()`

**Comment by sylbru** [comment]
@airtonjr This is for Slim 3, right? There isn’t much information about these helper methods being removed in Slim 4, but apparently they are. What is the usual way to go about this? Define your own PSR7 Request/Response extensions (with methods such as `isXhr`, `write`, `withRedirect`? Or just stop using them since it makes your app dependent on your own implementation and prevent you from switching to another one?
I actually found out about this before even trying to migrate to Slim 4, just because I set up Intelephense, that told me I was using these methods while they weren’t part of the PSR7 interface. It got me wondering what is the proper way to do this.

**Comment by odan** [comment]
This is for Slim 4. You could use the Slim-Http decorators (as per the docs) or you could use custom Renderer classes (e.g. a JsonRenderer,  HtmlRenderer etc..) for this purpose.

**Comment by sylbru** [comment]
Oh ok, interesting! Since the mentions of `write` and `withJson` among others had disappeared from the docs, and from [slimphp/Slim](https://github.com/slimphp/Slim/) codebase, and I couldn’t find them either in [slimphp/Slim-Psr7](https://github.com/slimphp/Slim-Psr7/), I assumed they were gone. Thanks for the information!

**Comment by olivertappin** [comment]
For a valid JSON response, this can either be written as:

```
$response->getBody()->write(json_encode(['foo' => 'bar']));
return $response->withHeader('Content-Type', 'application/json')->withStatus(201);
```

Or, if you do `composer require slim/http` and replace all instances of:

```
Slim\Http\Response as Response
```

with

```
Psr\Http\Message\ResponseInterface as Response
```

_(Don't forget you'll need to do the same with `Slim\Http\Request` if you're using it)_

And then you can use:

```
return $response->withJson(['foo' => 'bar'], 201);
```
