### ISSUE TITLE
Slim & Twig : 'ErrorException' with message 'require_once(/Autoloader.php)'

### ISSUE THREAD

**Issue by nicosomb** [slimphp/Slim#589]
Hello, 
I installed Slim & Twig with composer.

Here is my composer.json 

``` json
{
    "require": {
        "slim/slim": "2.*",
        "slim/views": "0.1.*"
    }
}
```

Here are my folders : 
templates\
templates\home.html
vendor\
vendor\composer
vendor\slim
vendor\autoload.php
index.php
composer.json
composer.phar
composer.lock

Here is my index.php : 

``` php
<?php
require 'vendor/autoload.php';

$app = new \Slim\Slim(array(
    'view' => new \Slim\Views\Twig()
));

$app->get('/', function () use ($app) {
    $app->render('home.html');
});

$app->run();
```

I've got this error : 

``` log
[Tue Jul 30 13:14:17 2013] [error] [client 127.0.0.1] PHP Warning:  Uncaught exception 'ErrorException' with message 'require_once(/Autoloader.php): failed to open stream: No such file or directory' in /home/nico/Dev/slim/vendor/slim/views/Slim/Views/Twig.php:114\nStack trace:\n#0 /home/nico/Dev/slim/vendor/slim/views/Slim/Views/Twig.php(114): Slim\\Slim::handleErrors(2, 'require_once(/A...', '/home/nico/Dev...', 114, Array)\n#1 /home/nico/Dev/slim/vendor/slim/views/Slim/Views/Twig.php(114): Slim\\Views\\Twig::getInstance()\n#2 /home/nico/Dev/slim/vendor/slim/views/Slim/Views/Twig.php(85): Slim\\Views\\Twig->getInstance()\n#3 /home/nico/Dev/slim/vendor/slim/slim/Slim/View.php(252): Slim\\Views\\Twig->render('home.html')\n#4 /home/nico/Dev/slim/vendor/slim/slim/Slim/View.php(242): Slim\\View->fetch('home.html')\n#5 /home/nico/Dev/slim/vendor/slim/slim/Slim/Slim.php(742): Slim\\View->display('home.html')\n#6 /home/nico/Dev/slim/index.php(11): Slim\\Slim->render('home.html')\n#7 [internal function]: {closure}()\n#8 /home/nico/Dev/slim/vendor/slim/slim/Slim/Route.php(436): call_user_func_a in /home/nico/Dev/slim/vendor/slim/views/Slim/Views/Twig.php on line 114
[Tue Jul 30 13:14:17 2013] [error] [client 127.0.0.1] PHP Fatal error:  Slim\\Views\\Twig::getInstance(): Failed opening required '/Autoloader.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/nico/Dev/slim/vendor/slim/views/Slim/Views/Twig.php on line 114
```

The code which gives the error is this code : 

``` php
            if (!class_exists('\Twig_Autoloader')) {
                require_once $this->parserDirectory . '/Autoloader.php';
            }
```

I searched Autoloader.php file, and it doesn't exist. 

How can I resolve this problem ? 

Thank you.

**Comment by nicosomb** [comment]
Sorry ...

I have to change public $parserDirectory = null; into public $parserDirectory = 'Twig'; in vendor/slim/views/Slim/Views/Twig.php file;

**Comment by nicosomb** [comment]
It's better to do this in your app : 

``` php
$view = $app->view();
$view->parserDirectory = 'Twig';
```

**Comment by ersmtp** [comment]
For me parserDirectory is NOT a valid parameter inside of Slim Views .. ?

**Comment by vnikodijevic** [comment]
Change your **composer.json** to include twig into repository:

```
{
    "require": {
        "slim/slim": "2.*",
        "slim/views": "0.1.*",
        "twig/twig": "1.*"
    }
}
```

Remove code from **Slim/Views/Twig.php** :

```
if (!class_exists('\Twig_Autoloader')) {
    require_once $this->parserDirectory . '/Autoloader.php';
}
```

Yahoooo - composer's autoloader loads twig's **Autoloader.php** class.

Cheers, 
Vukasin
