### ISSUE TITLE
halt() in middleware call throws exception

### ISSUE THREAD

**Issue by janeczku** [slimphp/Slim#756]
The code:

```
class LoginMiddleware extends \Slim\Middleware {
(...)
    public function call() {
        $app = $this->app
        $request = $app->request;
        (...)
        $app->response->headers->set('WWW-Authenticate', 'Basic realm="Bla"');
        $app->halt(401,'Please authenticate');
        (...)
     }
}
```

The result:

```
ERROR - 2013-10-29T06:39:30+01:00 - exception 'Slim\Exception\Stop' in /var/www/virtual/janeczku/html/books/vendor/slim/slim/Slim/Slim.php:1001
Stack trace:
#0 /var/www/virtual/janeczku/html/books/vendor/slim/slim/Slim/Slim.php(1021): Slim\Slim->stop()
#1 /var/www/virtual/janeczku/html/books/lib/BicBucStriim/login_middleware.php(50): Slim\Slim->halt(401, 'Please authenti...')
#2 /var/www/virtual/janeczku/html/books/lib/BicBucStriim/own_config_middleware.php(36): LoginMiddleware->call()
#3 /var/www/virtual/janeczku/html/books/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): OwnConfigMiddleware->call()
#4 /var/www/virtual/janeczku/html/books/vendor/slim/slim/Slim/Slim.php(1251): Slim\Middleware\PrettyExceptions->call()
#5 /var/www/virtual/janeczku/html/books/index.php(188): Slim\Slim->run()
#6 {main}   
```

What's going on???

**Comment by ciaranmaher** [comment]
Have a look at http://docs.slimframework.com/#Route-Helpers

Basically `halt()`, `pass()`, `redirect()` and `stop()` will throw a `\Slim\Exception\Stop` or `\Slim\Exception\Pass` exception as a way to stop user code from processing.
