### ISSUE TITLE
Allowing Access to a single route in a group unless user authenticated

### ISSUE THREAD

**Issue by r3wt** [slimphp/Slim#999]
`$app` is a DI Container wrapped around `Slim` and `Twig` with aliases to all slim/twig methods. The

``` php
$app->group('/admin',function() use ($app){

    if( !$app->is_admin() && $app->args['path'] != '/admin/auth' ) {
        $app->redirect('/admin/auth');
    }

});
```

The above code results in this error in `HHVM 3.5.0` for any route other than /admin/auth when not logged in : 

```
\nFatal error: Uncaught exception 'Slim\\Exception\\Stop' with message '' in 

/usr/share/nginx/html/crossbows/libs/vendor/slim/slim/Slim/Slim.php:1017\nStack trace:\n#0 

/usr/share/nginx/html/crossbows/libs/vendor/slim/slim/Slim/Slim.php(1037): Slim\\Slim->stop()\n#1 

/usr/share/nginx/html/crossbows/libs/vendor/slim/slim/Slim/Slim.php(1100): Slim\\Slim->halt()\n#2 

/usr/share/nginx/html/crossbows/libs/custom/allcrossbows.php(70): Slim\\Slim->redirect()\n#3 

/usr/share/nginx/html/crossbows/admin_routes.php(5): AllCrossbows\\App->redirect()\n#4 (): 

{closure}()\n#5 /usr/share/nginx/html/crossbows/libs/vendor/slim/slim/Slim/Slim.php(553): 

call_user_func()\n#6 /usr/share/nginx/html/crossbows/libs/custom/allcrossbows.php(62): 

Slim\\Slim->group()\n#7 /usr/share/nginx/html/crossbows/admin_routes.php(87): AllCrossbows\\App->group()\n#8
 /usr/share/nginx/html/crossbows/index.php(109): include()\n#9 {main}
```

I was hoping to avoid having to place this code in each individual route callback.

**Comment by mrzmyr** [comment]
How did you solve it ?

**Comment by lalop** [comment]
You need to use route middleware to do that
